const sportsArray = [
    {
      displayName: "FOOTBALL",
      logoUrl: "https://backend-eepj.vercel.app/photos/football.jpg",
      name: "football",
      handleDirectResult: false,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "BASKETBALL",
      logoUrl: "https://backend-eepj.vercel.app/photos/Basketball.jpg",
      name: "basketball",
      handleDirectResult: false,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "BASEBALL",
      logoUrl: "https://backend-eepj.vercel.app/photos/Baseball.jpg",
      name: "baseball",
      handleDirectResult: false,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "HOCKEY",
      logoUrl: "https://backend-eepj.vercel.app/photos/Hockey.jpg",
      name: "hockey",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "TENNIS",
      logoUrl: "https://backend-eepj.vercel.app/photos/Tennis.jpg",
      name: "tennis",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "AMERICAN FOOTBALL",
      logoUrl: "https://backend-eepj.vercel.app/photos/American Football.jpg",
      name: "american-football",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "AUSSIE RULES",
      logoUrl: "https://backend-eepj.vercel.app/photos/Aussie Rules.jpg",
      name: "aussie-rules",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "BADMINTON",
      logoUrl: "https://backend-eepj.vercel.app/photos/badminton_cleanup.jpg",
      name: "badminton",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "BOXING",
      logoUrl: "https://backend-eepj.vercel.app/photos/Boxing.jpg",
      name: "boxing",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "CRICKET",
      logoUrl: "https://backend-eepj.vercel.app/photos/Cricket.jpg",
      name: "cricket",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "DARTS",
      logoUrl: "https://backend-eepj.vercel.app/photos/Darts.jpg",
      name: "darts",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "ESPORTS",
      logoUrl: "https://backend-eepj.vercel.app/photos/esports.jpg",
      name: "esports",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "FUTSAL",
      logoUrl: "https://backend-eepj.vercel.app/photos/Futsal.jpg",
      name: "futsal",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "HANDBALL",
      logoUrl: "https://backend-eepj.vercel.app/photos/Handball.jpg",
      name: "handball",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "MMA",
      logoUrl: "https://backend-eepj.vercel.app/photos/MMA.jpg",
      name: "mma",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "RUGBY LEAGUE",
      logoUrl: "https://backend-eepj.vercel.app/photos/Rugby League.jpg",
      name: "rugby-league",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "RUGBY UNION",
      logoUrl: "https://backend-eepj.vercel.app/photos/Rugby Union.jpg",
      name: "rugby-union",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "TABLE TENNIS",
      logoUrl: "https://backend-eepj.vercel.app/photos/table tennis.jpg",
      name: "table-tennis",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "VOLLEYBALL",
      logoUrl: "https://backend-eepj.vercel.app/photos/Volleyball.jpg",
      name: "volleyball",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
    {
      displayName: "WATER POLO",
      logoUrl: "https://backend-eepj.vercel.app/photos/Water Polo.jpg",
      name: "water-polo",
      handleDirectResult: true,
      partialSum: 2,
      enabled: true,
    },
  ];

  export {sportsArray}